
deps = [
    "//third-party:derive-syn-parse",
    "//third-party:itertools",
    "//third-party:proc-macro2",
    "//third-party:quote",
    "//third-party:syn",
    "//third-party:unescape"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "sui-open-rpc-macros",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-open-rpc-macros",
    env = env,
    deps = deps,
    proc_macro = True,
)
