
deps = [
    "//crates/shared-crypto:shared-crypto",
    "//crates/sui-genesis-builder:sui-genesis-builder",
    "//crates/sui-move-build:sui-move-build",
    "//crates/sui-sdk:sui-sdk",
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//third-party:bcs"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "sui-test-transaction-builder",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-test-transaction-builder",
    env = env,
    deps = deps,
)
