mysten_deps = [
    "//external-crates/move/move-command-line-common:move-command-line-common",
    "//external-crates/move/move-binary-format:move-binary-format",
    "//external-crates/move/move-core/types:move-core-types",
    "//external-crates/move/move-ir/types:move-ir-types",
    "//external-crates/move/move-symbol-pool:move-symbol-pool",
]
rust_library(
    name="move-bytecode-source-map",
    srcs = glob(["src/**/*.rs"]),
    deps = mysten_deps + [
        "//third-party:anyhow",
        "//third-party:bcs",
        "//third-party:serde",
    ],
    visibility=["PUBLIC"],
)