
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[The Move Contributors]",
    "CARGO_PKG_NAME": "move-abstract-stack",
    "CARGO_PKG_VERSION": "0.0.1",
}
rust_library(
    name = "move-abstract-stack",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    edition = "2021",
    visibility = ["PUBLIC"]
)
