
deps = [
    "//crates/sui-protocol-config:sui-protocol-config",
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-vm-config:move-vm-config",
    "//external-crates/move/move-execution/next-vm/crates/move-bytecode-verifier:move-bytecode-verifier-next-vm",
    "//external-crates/move/move-execution/next-vm/crates/move-vm-runtime:move-vm-runtime-next-vm",
    "//external-crates/move/move-execution/v0/move-bytecode-verifier:move-bytecode-verifier-v0",
    "//external-crates/move/move-execution/v0/move-vm/runtime:move-vm-runtime-v0",
    "//external-crates/move/move-execution/v1/crates/move-bytecode-verifier:move-bytecode-verifier-v1",
    "//external-crates/move/move-execution/v1/crates/move-vm-runtime:move-vm-runtime-v1",
    "//sui-execution/latest/sui-adapter:sui-adapter-latest",
    "//sui-execution/latest/sui-move-natives:sui-move-natives-latest",
    "//sui-execution/latest/sui-verifier:sui-verifier-latest",
    "//sui-execution/next-vm/sui-adapter:sui-adapter-next-vm",
    "//sui-execution/next-vm/sui-move-natives:sui-move-natives-next-vm",
    "//sui-execution/next-vm/sui-verifier:sui-verifier-next-vm",
    "//sui-execution/v0/sui-adapter:sui-adapter-v0",
    "//sui-execution/v0/sui-move-natives:sui-move-natives-v0",
    "//sui-execution/v0/sui-verifier:sui-verifier-v0",
    "//sui-execution/v1/sui-adapter:sui-adapter-v1",
    "//sui-execution/v1/sui-move-natives:sui-move-natives-v1",
    "//sui-execution/v1/sui-verifier:sui-verifier-v1"
]
named_deps = {
    "move-bytecode-verifier-latest": "//external-crates/move/crates/move-bytecode-verifier:move-bytecode-verifier",
    "move-vm-runtime-latest": "//external-crates/move/crates/move-vm-runtime:move-vm-runtime"
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <eng@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Multiplexer to choose between multiple versions of sui and move execution crates.",
    "CARGO_PKG_NAME": "sui-execution",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-execution",
    env = env,
    deps = deps,
    named_deps = named_deps,
)
