mysten_deps = []
rust_library(
    name="typed-store-derive",
    srcs = ["src/lib.rs"],
    deps = mysten_deps + [
        "//third-party:proc-macro2",
        "//third-party:syn_v1",
        "//third-party:quote",
    ],
    proc_macro = True,
    visibility=["PUBLIC"],
)