
deps = [
    "//external-crates/move/testing-infra/enum-compat-util:enum-compat-util",
    "//third-party:quote",
    "//third-party:syn",
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "",
    "CARGO_PKG_NAME": "move-proc-macros",
    "CARGO_PKG_VERSION": "0.1.0",
}

rust_library(
    name = "move-proc-macros",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    proc_macro = True,
    # license = "Apache-2.0",
    edition = "2021",
    visibility = ["PUBLIC"],
    deps = deps
)
