mysten_deps = [
    "//external-crates/move/testing-infra/enum-compat-util:enum-compat-util",
]
rust_library(
    name="move-proc-macros",
    srcs = glob(["src/**/lib.rs"]),
    deps = mysten_deps + [
        "//third-party:serde_yaml",
        "//third-party:quote",
        "//third-party:syn",
    ],
    proc_macro = True,
    visibility=["PUBLIC"],
)