# extra_mapped_srcs = { "lz4.h" = "../lz4-sys-1.9.4/liblz4/lib/lz4.h", "zstd.h" = "../zstd-sys-2.0.8+zstd.1.5.5/zstd/lib/zstd.h" }
# extra_mapped_srcs = { "zstd.h" = "../zstd-sys-2.0.8+zstd.1.5.5/zstd/lib/zstd.h" }
# extra_mapped_srcs = { "sqlite3/bindgen_bundled_version.rs" = "src/bindgen.rs" }
extra_srcs = [
    "src/**/*.rs",
    "rocksdb/**/*.h",
    "../*lz4-sys*/**/*.h",
    "../*zstd-sys*/**/*.h",
    # "build_version.cc",
    "rocksdb/**/*.cc",
    "rocksdb/**/*.cc.in",
]
# omit_features = ["default", "libz-sys", "lz4-sys", "static", "zstd-sys"]

# omit_features = ["io-uring"]
# features = [
#     "bzip2",
#     # "io-uring",
#     "jemalloc",
#     "lz4",
#     "rtti",
#     "snappy",
#     "static",
#     "zlib",
#     "zstd",
# ]

# omit_features = ["io-uring"]
features = [
    # "bzip2",
    # "io-uring",
    # "jemalloc",
    "snappy",
    "lz4-sys",
    "libz-sys",
    "zstd-sys",
]

# ["lz4", "snappy", "zlib", "zstd"] 

# extra_deps = [
#     ":bzip2-sys-0.1.11+1.0.8",
#     ":libc-0.2.148",
#     ":libz-sys-1.1.12",
#     ":lz4-sys-1.9.4",
#     ":zstd-sys-2.0.8+zstd.1.5.5",
# ]
cargo_env = true
# buildscript = []
[[buildscript]]
[buildscript.rustc_flags]

[[buildscript]]
[buildscript.gen_srcs]

# buildscript = []
# [[platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.buildscript]]
# [platform_fixup.'cfg(all(target_arch = "aarch64", target_os = "macos"))'.buildscript.cxx_library]
# name = "librocksdb-sys-macos-arm64"
# srcs = [
#     "*.cc",
#     "cache/**/*.cc",
#     "db/**/*.cc",
#     "env/**/*.cc",
#     "file/**/*.cc",
#     "logging/**/*.cc",
#     "memory/**/*.cc",
#     "memtable/**/*.cc",
#     "monitoring/**/*.cc",
#     "options/**/*.cc",
#     "port/**/*.cc",
#     "table/**/*.cc",
#     "test_util/**/*.cc",
#     "tools/**/*.cc",
#     "trace_replay/**/*.cc",
#     "util/**/*.cc",
#     "utilities/**/*.cc",
# ]
# headers = ["*.h", "rocksdb/**/*.h", "snappy**/*.h"]
# exclude = ["build_version.cc"]
# include_paths = ["rocksdb/include", "snappy/"]
# compiler_flags = ["-Wno-error"]
