
buildscript = []
[[platform_fixup.'cfg(target_os = "linux")'.buildscript]]
[platform_fixup.'cfg(target_os = "linux")'.buildscript.cxx_library]
name = "bzip2-sys-linux"
srcs=[
    "bzip2-1.0.8/blocksort.c",
    "bzip2-1.0.8/huffman.c",
    "bzip2-1.0.8/crctable.c",
    "bzip2-1.0.8/randtable.c",
    "bzip2-1.0.8/compress.c",
    "bzip2-1.0.8/decompress.c",
    "bzip2-1.0.8/bzlib.c",
]
include_paths = [
    "bzip2-1.0.8/",
]
compiler_flags = [
    "-D_FILE_OFFSET_BITS=64",
    "-DBZ_NO_STDIO",
    "-Wno-error",
]
[env]
OUT_DIR = "."
