# cfgs = ["tokio_unstable", "tokio_track_caller"]

extra_srcs = ["src/**/*.rs"]

buildscript = []
# features = ["tokio_track_caller", "signal"]
features = ["full"]
# extra_deps = [":tracing", ":libc"]
