  
named_deps = {
    "atomic_float":"//third-party:atomic_float_v0_1",
    "bytes-varint":"//third-party:bytes-varint_v1",
    "bytes":"//third-party:bytes_v1",
    "clap":"//third-party:clap_v4",
    "console-subscriber":"//third-party:console-subscriber_v0_2",
    "crossterm":"//third-party:crossterm_v0_25",
    "futures":"//third-party:futures_v0_3",
    "once_cell":"//third-party:once_cell_v1",
    "opentelemetry-otlp":"//third-party:opentelemetry-otlp_v0_13",
    "opentelemetry-proto":"//third-party:opentelemetry-proto_v0_3",
    "opentelemetry_api":"//third-party:opentelemetry_api_v0_20",
    "opentelemetry":"//third-party:opentelemetry_v0_20",
    "prometheus":"//third-party:prometheus_v0_13",
    "prost":"//third-party:prost_v0_11",
    "tokio":"//third-party:tokio_v1",
    "tonic":"//third-party:tonic_v0_9",
    "tracing-appender":"//third-party:tracing-appender_v0_2",
    "tracing-opentelemetry":"//third-party:tracing-opentelemetry_v0_21",
    "tracing-subscriber":"//third-party:tracing-subscriber_v0_3",
    "tracing":"//third-party:tracing_v0_1",
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Evan Chan <echan@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Library for common telemetry and observability functionality",
    "CARGO_PKG_NAME": "telemetry-subscribers",
    "CARGO_PKG_VERSION": "0.2.0",
}

rust_library(
    name = "telemetry-subscribers",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env, 
    features = ["otlp"],
    # license = "Apache-2.0",
    edition = "2021", 
    named_deps = named_deps, 
    visibility = ["PUBLIC"],
)
