# load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
# system_demo_toolchains()

load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude//toolchains:go.bzl", "system_go_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")


system_genrule_toolchain(
    name="genrule",
    visibility=["PUBLIC"],
)

system_rust_toolchain(
    name="rust",
    default_edition="2021",
    visibility=["PUBLIC"],
)

system_cxx_toolchain(
    name="cxx",
    linker=select(
        {
            "config//os:macos": "clang++",
            "config//os:linux": "clang++",
        }
    ),
    visibility=["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name="python_bootstrap",
    visibility=["PUBLIC"],
)
