[package]
authors = [
  "Jk Jensen <jk@mystenlabs.com>",
  "Mysten Labs <build@mystenlabs.com>",
]
edition = "2021"
license = "Apache-2.0"
name = "suiop-cli"
publish = false
version = "0.1.8"

[lib]
name = "suioplib"
path = "src/lib.rs"

[[bin]]
name = "suiop"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
colored.workspace = true
docker-api.workspace = true
field_names.workspace = true
include_dir.workspace = true
inquire.workspace = true
prettytable-rs.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = [
  "rustls-tls",
  "json",
], default-features = false }
semver.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
spinners.workspace = true
strum.workspace = true
tokio = { workspace = true, features = ["full"] }
toml_edit.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
