
deps = [
    "//third-party:bcs",
    "//third-party:schemars",
    "//third-party:serde",
    "//third-party:serde_json",
    "//third-party:versions"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "sui-open-rpc",
    "CARGO_PKG_VERSION": "1.16.0",
}
rust_library(
    name = "sui-open-rpc",
    env = env,
    deps = deps,
)
