
deps = [
    "//third-party:anyhow",
    "//third-party:hex",
    "//third-party:log",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-command-line-common:move-command-line-common",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-docgen:move-docgen",
    "//external-crates/move/crates/move-errmapgen:move-errmapgen",
    "//external-crates/move/crates/move-prover:move-prover",
    "//external-crates/move/crates/move-vm-types:move-vm-types",
    "//third-party:sha2",
    "//third-party:sha3",
    "//third-party:smallvec",
    "//third-party:walkdir", 
named_deps = {
    "move-vm-runtime-v0":"//external-crates/move/move-execution/v0/move-vm/runtime:",
}
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Diem Association <opensource@diem.com>]",
    "CARGO_PKG_DESCRIPTION": "Diem stdlib",
    "CARGO_PKG_NAME": "move-stdlib-v0",
    "CARGO_PKG_VERSION": "0.1.1",
}

rust_library(
    name = "move-stdlib-v0",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    # license = "Apache-2.0",
    edition = "2021",
    visibility = ["PUBLIC"],
    deps = deps
)
