
deps = [
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-abstract-stack:move-abstract-stack",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-bytecode-utils:move-bytecode-utils",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-vm-config:move-vm-config"
]
named_deps = {
    "move-bytecode-verifier": "//external-crates/move/move-execution/next-vm/crates/move-bytecode-verifier:move-bytecode-verifier-next-vm"
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <eng@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Move framework for Sui platform",
    "CARGO_PKG_NAME": "sui-verifier-next-vm",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-verifier-next-vm",
    env = env,
    deps = deps,
    named_deps = named_deps,
)
