
deps = [
    "//third-party:serde_yaml",
] 
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "",
    "CARGO_PKG_NAME": "enum-compat-util",
    "CARGO_PKG_VERSION": "0.1.0",
}

rust_library(
    name = "enum-compat-util",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    # license = "Apache-2.0",
    edition = "2021",
    visibility = ["PUBLIC"], 
    deps = deps
)
