
deps = [
    "//third-party:serde_yaml_0_8_26"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "enum-compat-util",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "enum-compat-util",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    deps = deps,
    edition = "2021",
    visibility = ["PUBLIC"]
)
