[package]
name = "mysten-service-boilerplate"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
mysten-service.workspace = true
prometheus.workspace = true
tracing.workspace = true
axum.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
