
deps = [
    "//crates/simulacrum:simulacrum",
    "//crates/sui-core:sui-core",
    "//crates/sui-types:sui-types",
    "//third-party:anyhow",
    "//third-party:axum",
    "//third-party:bcs",
    "//third-party:rand",
    "//third-party:reqwest",
    "//third-party:serde"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[]",
    "CARGO_PKG_NAME": "sui-rest-api",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-rest-api",
    env = env,
    deps = deps,
)
