rust_binary(
    name="sui-proxy",
    # srcs=select({
    #     "config//os:linux": glob(["src/**/*.rs"]),
    #     "config//os:macos": glob(["src/**/*.rs"]),
    # }),
    srcs = glob(["src/**/*.rs"]),
    crate_root="src/main.rs",
    env={
        "CARGO_PKG_AUTHORS": "Mysten Labs <build@mystenlabs.com>",
        "CARGO_BIN_NAME": "hagent",
        "CARGO_PKG_VERSION": "0.0.2",
        "CARGO_PKG_NAME": "ugh",
        # "CARGO_PKG_VERSION_MAJOR": "0",
        # "CARGO_PKG_VERSION_MINOR": "3",
        # "CARGO_PKG_VERSION_PATCH": "28",
    },
    deps=[
        # "//third-party:mio",
        "//third-party:axum",
        "//third-party:axum-server",
        "//third-party:anyhow",
        "//third-party:bytes",
        "//third-party:tokio",
        "//third-party:clap",
        "//third-party:reqwest",
        "//third-party:serde_json",
        "//third-party:prometheus-parse",
        "//third-party:prometheus",
        "//third-party:tracing",
        "//third-party:tower-http",
        "//third-party:tower",
        "//third-party:git-version",
        "//third-party:once_cell",
        "//third-party:const-str",
    ],
    visibility=["PUBLIC"],
)



# sui-tls.workspace = true
# sui-types.workspace = true
# mysten-metrics.workspace = true
# telemetry-subscribers.workspace = true

mysten_deps = [
    # "//crates/sui-tls:sui-tls",
    "//crates/sui-types:sui-types",
    "//crates/mysten-metrics:mysten-metrics",
]

rust_library(
    name="foo",
    # srcs = glob(["src/**/*.rs"]),
    srcs = ["src/foo.rs"],
    crate_root="src/foo.rs",
    deps = mysten_deps + [
        # "//third-party:mio",
        "//third-party:axum",
        "//third-party:axum-server",
        "//third-party:anyhow",
        "//third-party:bytes",
        "//third-party:tokio",
        "//third-party:clap",
        "//third-party:reqwest",
        "//third-party:rand",
        "//third-party:hyper",
        "//third-party:protobuf",
        "//third-party:itertools",
        "//third-party:serde",
        "//third-party:serde_with",
        "//third-party:serde_yaml",
        "//third-party:serde_json",
        # "//third-party:prometheus-parse",
        "//third-party:prometheus",
        "//third-party:tracing",
        "//third-party:tower-http",
        "//third-party:tower",
        "//third-party:git-version",
        "//third-party:once_cell",
        "//third-party:const-str",
        "//third-party:multiaddr",
        "//third-party:snap",
        "//third-party:rustls",
        "//third-party:rustls-pemfile",
        "//third-party:http-body",
        "//third-party:fastcrypto",
    ],
)