
deps = [
    "//crates/sui-core:sui-core",
    "//third-party:reqwest",
    "//third-party:serde",
    "//third-party:tracing"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "sui-telemetry",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-telemetry",
    env = env,
    deps = deps,
)
