[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
axum = "0.6.12"
# axum-server = { version = "0.4.7", default-features = false }
# anyhow = { version = "1.0.64", features = ["backtrace"] }
# tokio = "1.28.1"
# clap = { version = "4.4", features = ["derive", "wrap_help"] }
# reqwest = { version = "0.11.20", default_features = false, features = [
#     "blocking",
#     "json",
#     "rustls-tls",
# ] }
# prometheus-parse = { git = "https://github.com/suiwombat/prometheus-parse-rs.git" }
# prometheus = "0.13.3"
# const-str = "0.5.3"
# mio = "0.8.8"
# socket2 = "0.5.4"
# libc = "0.2"
# bytes = "1.4.0"
# protobuf = { version = "2.28", features = ["with-bytes"] }
# tracing = "0.1.37"
# tower = { version = "0.4.12", features = [
#     "full",
#     "util",
#     "timeout",
#     "load-shed",
#     "limit",
# ] }
# tower-http = { version = "0.3.4", features = [
#     "cors",
#     "full",
#     "trace",
#     "set-header",
#     "propagate-header",
# ] }
# serde = { version = "1.0.144", features = ["derive", "rc"] }
# serde_json = { version = "1.0.95", features = [
#     "preserve_order",
#     "arbitrary_precision",
# ] }
# serde_with = { version = "2.1.0", features = ["hex"] }
# serde_yaml = "0.8.26"
# git-version = "0.3.5"
# itertools = "0.10.5"
# rand = "0.8.5"
# hyper = "0.14.20"
# multiaddr = "0.17.0"
# snap = "1.1.0"
# rustls = { version = "0.21.6", features = ["dangerous_configuration"] }
# rustls-pemfile = "1.0.2"
# once_cell = "1.18.0"
# http-body = "0.4.5"
# fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "3547ed059927007c7ff48e729ed59da3dbb6a2e3" }

# Local patches - typically git references
[patch.crates-io]
