
deps = [
    "//third-party:anemo",
    "//third-party:fastcrypto",
    "//third-party:fdlimit",
    "//third-party:indexmap",
    "//third-party:itertools",
    "//crates/mysten-metrics:mysten-metrics",
    "//crates/mysten-network:mysten-network",
    "//third-party:once_cell",
    "//third-party:prometheus",
    "//third-party:rand",
    "//crates/sui-protocol-config:sui-protocol-config",
    "//crates/telemetry-subscribers:telemetry-subscribers",
    "//third-party:tempfile",
    "//third-party:tokio",
    "//third-party:tonic",
    "//third-party:tracing",
] 
named_deps = {
    "config":"//narwhal/config:narwhal-config",
    "crypto":"//narwhal/crypto:narwhal-crypto",
    "executor":"//narwhal/executor:narwhal-executor",
    "network":"//narwhal/network:narwhal-network",
    "node":"//narwhal/node:narwhal-node",
    "primary":"//narwhal/primary:narwhal-primary",
    "storage":"//narwhal/storage:narwhal-storage",
    "store":"//crates/typed-store:typed-store",
    "types":"//narwhal/types:narwhal-types",
    "worker":"//narwhal/worker:narwhal-worker",
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "",
    "CARGO_PKG_NAME": "narwhal-test-utils",
    "CARGO_PKG_VERSION": "0.1.0",
}

rust_library(
    name = "narwhal-test-utils",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    # license = "Apache-2.0",
    edition = "2021",
    visibility = ["PUBLIC"], 
    named_deps = named_deps,
    deps = deps
)
