
[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anemo_0_0_0 = {git="https://github.com/mystenlabs/anemo.git",rev="1169850e6af127397068cd86764c29b1d49dbe35",package="anemo"}
anyhow_1_0_71 = {version="1.0.71",package="anyhow",features=["backtrace","std"]}
arbitrary_1_3_0 = {version="1.3.0",package="arbitrary",features=["derive","derive_arbitrary"]}
async-trait_0_1_73 = {version="0.1.73",package="async-trait"}
atomic_float_0_1_0 = {version="0.1.0",package="atomic_float",features=["atomic_f64"]}
axum-server_0_5_1 = {version="0.5.1",package="axum-server",features=["arc-swap","pin-project-lite","rustls","rustls-pemfile","tls-rustls","tokio-rustls"]}
axum_0_6_20 = {version="0.6.20",package="axum",features=["form","headers","http1","http2","json","matched-path","original-uri","query","tokio","tower-log","ws"]}
bcs_0_1_4 = {version="0.1.4",package="bcs"}
bincode_1_3_3 = {version="1.3.3",package="bincode"}
byteorder_1_4_3 = {version="1.4.3",package="byteorder",features=["i128","std"]}
bytes-varint_1_0_3 = {version="1.0.3",package="bytes-varint"}
bytes_1_4_0 = {version="1.4.0",package="bytes",features=["serde","std"]}
cfg-if_1_0_0 = {version="1.0.0",package="cfg-if"}
clap_4_4_1 = {version="4.4.1",package="clap",features=["color","derive","error-context","help","std","suggestions","usage","wrap_help"]}
codespan-reporting_0_11_1 = {version="0.11.1",package="codespan-reporting",features=["serde","serialization"]}
codespan_0_11_1 = {version="0.11.1",package="codespan",features=["serde","serialization"]}
colored_2_0_4 = {version="2.0.4",package="colored"}
const-str_0_5_6 = {version="0.5.6",package="const-str"}
crossterm_0_25_0 = {version="0.25.0",package="crossterm",features=["bracketed-paste"]}
dashmap_5_4_0 = {version="5.4.0",package="dashmap"}
derivative_2_2_0 = {version="2.2.0",package="derivative",features=["use_core"]}
derive_more_0_99_17 = {version="0.99.17",package="derive_more",features=["add","add_assign","as_mut","as_ref","constructor","convert_case","deref","deref_mut","display","error","from","from_str","index","index_mut","into","into_iterator","is_variant","iterator","mul","mul_assign","not","rustc_version","sum","try_into","unwrap"]}
difference_2_0_0 = {version="2.0.0",package="difference"}
dirs-next_2_0_0 = {version="2.0.0",package="dirs-next"}
ed25519-consensus_2_1_0 = {version="2.1.0",package="ed25519-consensus",features=["serde","std","thiserror"]}
ed25519_1_5_3 = {version="1.5.3",package="ed25519",features=["alloc","pkcs8","serde","std","zeroize"]}
enum_dispatch_0_3_9 = {version="0.3.9",package="enum_dispatch"}
ethnum_1_3_2 = {version="1.3.2",package="ethnum"}
eyre_0_6_8 = {version="0.6.8",package="eyre",features=["auto-install","track-caller"]}
fastcrypto-tbls_0_1_0 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto-tbls"}
fastcrypto-zkp_0_1_2 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto-zkp"}
fastcrypto_0_1_7 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto",features=["beacon-dkg","copy_key"]}
futures_0_3_29 = {version="0.3.29",package="futures",features=["alloc","async-await","bilock","executor","futures-executor","std","unstable"]}
git-version_0_3_5 = {version="0.3.5",package="git-version"}
hashbrown_0_12_3 = {version="0.12.3",package="hashbrown",features=["ahash","inline-more","raw"]}
hex_0_4_3 = {version="0.4.3",package="hex",features=["alloc","serde","std"]}
http-body_0_4_5 = {version="0.4.5",package="http-body"}
http_0_2_9 = {version="0.2.9",package="http"}
hyper_0_14_26 = {version="0.14.26",package="hyper",features=["client","full","h2","http1","http2","runtime","server","socket2","stream","tcp"]}
im_15_1_0 = {version="15.1.0",package="im"}
impl-trait-for-tuples_0_2_2 = {version="0.2.2",package="impl-trait-for-tuples"}
indexmap_1_9_3 = {version="1.9.3",package="indexmap",features=["serde","serde-1","std"]}
insta_1_26_0 = {version="1.26.0",package="insta",features=["colors","console","json","pest","pest_derive","redactions","serde","yaml"]}
itertools_0_10_5 = {version="0.10.5",package="itertools",features=["use_alloc","use_std"]}
log_0_4_20 = {version="0.4.20",package="log",features=["serde","std"]}
match_opt_0_1_2 = {version="0.1.2",package="match_opt"}
multiaddr_0_17_0 = {version="0.17.0",package="multiaddr",features=["url"]}
num-bigint_0_4_3 = {version="0.4.3",package="num-bigint",features=["rand","std"]}
num_0_4_1 = {version="0.4.1",package="num",features=["num-bigint","std"]}
once_cell_1_18_0 = {version="1.18.0",package="once_cell",features=["alloc","race","std","unstable"]}
opentelemetry-otlp_0_13_0 = {version="0.13.0",package="opentelemetry-otlp",features=["grpc-tonic","http","prost","tokio","tonic","trace"]}
opentelemetry-proto_0_3_0 = {version="0.3.0",package="opentelemetry-proto",features=["gen-tonic","gen-tonic-messages","prost","tonic","traces"]}
opentelemetry_0_20_0 = {version="0.20.0",package="opentelemetry",features=["metrics","rt-tokio","trace"]}
opentelemetry_api_0_20_0 = {version="0.20.0",package="opentelemetry_api",features=["logs","metrics","pin-project-lite","trace"]}
ouroboros_0_17_2 = {version="0.17.2",package="ouroboros",features=["std"]}
parking_lot_0_12_1 = {version="0.12.1",package="parking_lot"}
petgraph_0_5_1 = {version="0.5.1",package="petgraph",features=["graphmap","matrix_graph","stable_graph"]}
phf_0_11_1 = {version="0.11.1",package="phf",features=["macros","phf_macros","std","uncased"]}
pkcs8_0_9_0 = {version="0.9.0",package="pkcs8",features=["alloc","pem","std"]}
primitive-types_0_10_1 = {version="0.10.1",package="primitive-types",features=["impl-codec","impl-serde","std"]}
proc-macro2_1_0_66 = {version="1.0.66",package="proc-macro2",features=["proc-macro","span-locations"]}
prometheus_0_13_3 = {version="0.13.3",package="prometheus",features=["protobuf"]}
proptest-derive_0_3_0 = {version="0.3.0",package="proptest-derive"}
proptest_1_1_0 = {version="1.1.0",package="proptest",features=["bit-set","break-dead-code","fork","lazy_static","quick-error","regex-syntax","rusty-fork","std","tempfile","timeout"]}
prost_0_11_9 = {version="0.11.9",package="prost",features=["prost-derive","std"]}
prost_0_12_1 = {version="0.12.1",package="prost",features=["prost-derive","std"]}
protobuf_2_28_0 = {version="2.28.0",package="protobuf",features=["bytes","with-bytes"]}
quote_1_0_33 = {version="1.0.33",package="quote",features=["proc-macro"]}
rand_0_8_5 = {version="0.8.5",package="rand",features=["alloc","getrandom","libc","rand_chacha","small_rng","std","std_rng"]}
rcgen_0_9_3 = {version="0.9.3",package="rcgen",features=["pem"]}
ref-cast_1_0_14 = {version="1.0.14",package="ref-cast"}
regex_1_8_4 = {version="1.8.4",package="regex",features=["aho-corasick","memchr","perf","perf-cache","perf-dfa","perf-inline","perf-literal","std","unicode","unicode-age","unicode-bool","unicode-case","unicode-gencat","unicode-perl","unicode-script","unicode-segment"]}
reqwest_0_11_20 = {version="0.11.20",package="reqwest",features=["__rustls","__tls","blocking","hyper-rustls","json","rustls","rustls-pemfile","rustls-tls","rustls-tls-webpki-roots","serde_json","stream","tokio-rustls","tokio-util","wasm-streams","webpki-roots"]}
roaring_0_10_1 = {version="0.10.1",package="roaring"}
rustls-pemfile_1_0_2 = {version="1.0.2",package="rustls-pemfile"}
rustls-webpki_0_101_4 = {version="0.101.4",package="rustls-webpki",features=["alloc","std"]}
rustls_0_21_6 = {version="0.21.6",package="rustls",features=["dangerous_configuration","log","logging","quic","tls12"]}
schemars_0_8_12 = {version="0.8.12",package="schemars",features=["derive","either","schemars_derive"]}
scopeguard_1_1_0 = {version="1.1.0",package="scopeguard",features=["use_std"]}
serde-name_0_2_1 = {version="0.2.1",package="serde-name"}
serde-reflection_0_3_6 = {version="0.3.6",package="serde-reflection"}
serde_1_0_190 = {version="1.0.190",package="serde",features=["alloc","derive","rc","serde_derive","std"]}
serde_bytes_0_11_9 = {version="0.11.9",package="serde_bytes",features=["std"]}
serde_json_1_0_95 = {version="1.0.95",package="serde_json",features=["alloc","arbitrary_precision","indexmap","preserve_order","raw_value","std","unbounded_depth"]}
serde_repr_0_1_10 = {version="0.1.10",package="serde_repr"}
serde_with_2_1_0 = {version="2.1.0",package="serde_with",features=["alloc","hex","macros","std"]}
serde_yaml_0_8_26 = {version="0.8.26",package="serde_yaml"}
sha2_0_9_9 = {version="0.9.9",package="sha2",features=["std"]}
signature_1_6_4 = {version="1.6.4",package="signature",features=["digest","digest-preview","hazmat-preview","rand-preview","rand_core","std"]}
smallvec_1_10_0 = {version="1.10.0",package="smallvec"}
snap_1_1_0 = {version="1.1.0",package="snap"}
static_assertions_1_1_0 = {version="1.1.0",package="static_assertions"}
strum_0_24_1 = {version="0.24.1",package="strum",features=["derive","std","strum_macros"]}
strum_macros_0_24_3 = {version="0.24.3",package="strum_macros"}
syn_1_0_107 = {version="1.0.107",package="syn",features=["clone-impls","derive","extra-traits","fold","full","parsing","printing","proc-macro","quote","visit","visit-mut"]}
syn_2_0_32 = {version="2.0.32",package="syn",features=["clone-impls","derive","extra-traits","fold","full","parsing","printing","proc-macro","quote","visit","visit-mut"]}
synstructure_0_12_6 = {version="0.12.6",package="synstructure",features=["proc-macro"]}
tap_1_0_1 = {version="1.0.1",package="tap"}
tempfile_3_8_0 = {version="3.8.0",package="tempfile"}
thiserror_1_0_50 = {version="1.0.50",package="thiserror"}
tokio-rustls_0_24_0 = {version="0.24.0",package="tokio-rustls",features=["logging","tls12"]}
tokio-stream_0_1_14 = {version="0.1.14",package="tokio-stream",features=["net","sync","time","tokio-util"]}
tokio_1_28_1 = {version="1.28.1",package="tokio",features=["bytes","fs","full","io-std","io-util","libc","macros","mio","net","num_cpus","parking_lot","process","rt","rt-multi-thread","signal","signal-hook-registry","socket2","sync","test-util","time","tokio-macros","tracing","windows-sys"]}
tonic-health_0_10_2 = {version="0.10.2",package="tonic-health",features=["transport"]}
tonic_0_10_0 = {version="0.10.0",package="tonic",features=["channel","codegen","prost","tls","transport"]}
tonic_0_9_2 = {version="0.9.2",package="tonic",features=["channel","codegen","prost","transport"]}
tower-http_0_3_5 = {version="0.3.5",package="tower-http",features=["add-extension","async-compression","auth","base64","catch-panic","compression-br","compression-deflate","compression-full","compression-gzip","cors","decompression-br","decompression-deflate","decompression-full","decompression-gzip","follow-redirect","fs","full","httpdate","iri-string","limit","map-request-body","map-response-body","metrics","mime","mime_guess","normalize-path","percent-encoding","propagate-header","redirect","request-id","sensitive-headers","set-header","set-status","timeout","tokio","tokio-util","tower","trace","tracing","util","uuid","validate-request"]}
tower-layer_0_3_2 = {version="0.3.2",package="tower-layer"}
tower_0_4_13 = {version="0.4.13",package="tower",features=["__common","balance","buffer","discover","filter","full","futures-core","futures-util","hdrhistogram","hedge","indexmap","limit","load","load-shed","log","make","pin-project","pin-project-lite","rand","ready-cache","reconnect","retry","slab","spawn-ready","steer","timeout","tokio","tokio-util","tracing","util"]}
tracing-appender_0_2_2 = {version="0.2.2",package="tracing-appender"}
tracing-opentelemetry_0_21_0 = {version="0.21.0",package="tracing-opentelemetry",features=["metrics","smallvec","tracing-log"]}
tracing-subscriber_0_3_17 = {version="0.3.17",package="tracing-subscriber",features=["alloc","ansi","env-filter","fmt","json","matchers","nu-ansi-term","once_cell","regex","registry","serde","serde_json","sharded-slab","smallvec","std","thread_local","time","tracing","tracing-log","tracing-serde"]}
tracing_0_1_37 = {version="0.1.37",package="tracing",features=["attributes","log","std","tracing-attributes"]}
uint_0_9_5 = {version="0.9.5",package="uint",features=["std"]}
uuid_1_2_2 = {version="1.2.2",package="uuid",features=["fast-rng","getrandom","rand","rng","std","v4"]}
variant_count_1_1_0 = {version="1.1.0",package="variant_count"}
walkdir_2_3_2 = {version="2.3.2",package="walkdir"}
x509-parser_0_14_0 = {version="0.14.0",package="x509-parser"}
# hard-coded in buckify template
libc = "0.2"
# Local patches - typically git references
[patch.crates-io]
