[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anyhow_v1 = { package = "anyhow", version = "1.0.71" }
async-trait_v0_1 = { package = "async-trait", version = "0.1.61" }
atomic_float_v0_1 = { package = "atomic_float", version = "0.1" }
axum-server_v0_5 = { package = "axum-server", features = ["tls-rustls"], default-features = false, version = "0.5.1" }
axum_v0_6 = { package = "axum", features = ["form", "headers", "http1", "http2", "json", "matched-path", "original-uri", "query", "tokio", "ws"], default-features = false, version = "0.6.6" }
bcs_v0_1 = { package = "bcs", version = "0.1.4" }
bincode_v1 = { package = "bincode", version = "1.3.3" }
byteorder_v1 = { package = "byteorder", version = "1.4.3" }
bytes-varint_v1 = { package = "bytes-varint", default-features = false, version = "1" }
bytes_v1 = { package = "bytes", version = "1.4" }
cfg-if_v1 = { package = "cfg-if", version = "1" }
clap_v4 = { package = "clap", features = ["derive", "wrap_help"], version = "4.4" }
colored_v2 = { package = "colored", version = "2" }
console-subscriber_v0_2 = { package = "console-subscriber", version = "0.2" }
const-str_v0_5 = { package = "const-str", version = "0.5.3" }
crossterm_v0_25 = { package = "crossterm", version = "0.25" }
dashmap_v5 = { package = "dashmap", version = "5.4" }
derivative_v2 = { package = "derivative", version = "2.2" }
derive_more_v0_99 = { package = "derive_more", version = "0.99.17" }
ed25519-consensus_v2 = { package = "ed25519-consensus", features = ["serde"], version = "2.0.1" }
ed25519_v1 = { package = "ed25519", features = ["alloc", "pkcs8", "zeroize"], version = "1.5" }
enum_dispatch_v0_3 = { package = "enum_dispatch", version = "0.3" }
eyre_v0_6 = { package = "eyre", version = "0.6.8" }
futures_v0_3 = { package = "futures", version = "0.3.28" }
git-version_v0_3 = { package = "git-version", version = "0.3.5" }
hashbrown_v0_12 = { package = "hashbrown", version = "0.12" }
hex_v0_4 = { package = "hex", version = "0.4.3" }
http-body_v0_4 = { package = "http-body", version = "0.4.5" }
http_v0_2 = { package = "http", version = "0.2.8" }
hyper_v0_14 = { package = "hyper", version = "0.14.20" }
im_v15 = { package = "im", version = "15" }
impl-trait-for-tuples_v0_2 = { package = "impl-trait-for-tuples", version = "0.2" }
indexmap_v1 = { package = "indexmap", features = ["serde"], version = "1.9.2" }
insta_v1 = { package = "insta", features = ["json", "redactions", "yaml"], version = "1.21.1" }
itertools_v0_10 = { package = "itertools", version = "0.10.5" }
libc = "0.2"
match_opt_v0_1 = { package = "match_opt", version = "0.1.2" }
multiaddr_v0_17 = { package = "multiaddr", version = "0.17" }
num-bigint_v0_4 = { package = "num-bigint", version = "0.4.3" }
once_cell_v1 = { package = "once_cell", version = "1.18" }
opentelemetry-otlp_v0_13 = { package = "opentelemetry-otlp", features = ["grpc-tonic"], version = "0.13" }
opentelemetry-proto_v0_3 = { package = "opentelemetry-proto", features = ["gen-tonic", "traces"], version = "0.3" }
opentelemetry_api_v0_20 = { package = "opentelemetry_api", features = ["logs", "metrics"], version = "0.20" }
opentelemetry_v0_20 = { package = "opentelemetry", features = ["metrics", "rt-tokio"], version = "0.20" }
parking_lot_v0_12 = { package = "parking_lot", version = "0.12.1" }
petgraph_v0_5 = { package = "petgraph", version = "0.5.1" }
pkcs8_v0_9 = { package = "pkcs8", features = ["std"], version = "0.9" }
proc-macro2_v1 = { package = "proc-macro2", version = "1.0.47" }
prometheus_v0_13 = { package = "prometheus", version = "0.13.3" }
proptest-derive_v0_3 = { package = "proptest-derive", version = "0.3" }
proptest_v1 = { package = "proptest", version = "1.1" }
prost-build_v0_12 = { package = "prost-build", version = "0.12.1" }
prost_v0_11 = { package = "prost", version = "0.11" }
prost_v0_12 = { package = "prost", version = "0.12.1" }
protobuf_v2 = { package = "protobuf", features = ["with-bytes"], version = "2.28" }
quote_v1 = { package = "quote", version = "1.0.23" }
rand_v0_8 = { package = "rand", version = "0.8.5" }
rcgen_v0_9 = { package = "rcgen", version = "0.9.2" }
regex_v1 = { package = "regex", version = "1.7.1" }
reqwest_v0_11 = { package = "reqwest", features = ["blocking", "json", "rustls-tls"], version = "0.11.20" }
roaring_v0_10 = { package = "roaring", version = "0.10.1" }
rustls-pemfile_v1 = { package = "rustls-pemfile", version = "1.0.2" }
rustls_v0_21 = { package = "rustls", features = ["dangerous_configuration"], version = "0.21.6" }
schemars_v0_8 = { package = "schemars", features = ["either"], version = "0.8.10" }
scopeguard_v1 = { package = "scopeguard", version = "1.1" }
serde-name_v0_2 = { package = "serde-name", version = "0.2.1" }
serde-reflection_v0_3 = { package = "serde-reflection", version = "0.3.6" }
serde_json_v1 = { package = "serde_json", features = ["arbitrary_precision", "preserve_order"], version = "1.0.95" }
serde_repr_v0_1 = { package = "serde_repr", version = "0.1" }
serde_v1 = { package = "serde", features = ["derive", "rc"], version = "1.0.144" }
serde_with_v2 = { package = "serde_with", features = ["hex"], version = "2.1" }
serde_yaml_v0_8 = { package = "serde_yaml", version = "0.8.26" }
signature_v1 = { package = "signature", version = "1.6" }
smallvec_v1 = { package = "smallvec", version = "1.10" }
snap_v1 = { package = "snap", version = "1.1" }
static_assertions_v1 = { package = "static_assertions", version = "1.1" }
strum_macros_v0_24 = { package = "strum_macros", version = "0.24.3" }
strum_v0_24 = { package = "strum", features = ["derive"], version = "0.24" }
syn_v1 = { package = "syn", features = ["derive", "extra-traits", "full"], version = "1.0.104" }
syn_v2 = { package = "syn", features = ["extra-traits", "fold", "full", "visit", "visit-mut"], version = "2" }
synstructure_v0_12 = { package = "synstructure", version = "0.12" }
tap_v1 = { package = "tap", version = "1.0.1" }
tempfile_v3 = { package = "tempfile", version = "3.3" }
thiserror_v1 = { package = "thiserror", version = "1.0.40" }
tokio-rustls_v0_24 = { package = "tokio-rustls", version = "0.24" }
tokio-stream_v0_1 = { package = "tokio-stream", features = ["net", "sync"], version = "0.1.14" }
tokio_v1 = { package = "tokio", features = ["full"], version = "1.28.1" }
tonic-health_v0_10 = { package = "tonic-health", version = "0.10" }
tonic_v0_10 = { package = "tonic", features = ["tls", "transport"], version = "0.10" }
tonic_v0_9 = { package = "tonic", version = "0.9" }
tower-http_v0_3 = { package = "tower-http", features = ["cors", "full", "propagate-header", "set-header", "trace"], version = "0.3.4" }
tower-layer_v0_3 = { package = "tower-layer", version = "0.3.2" }
tower_v0_4 = { package = "tower", features = ["full", "limit", "load-shed", "timeout", "util"], version = "0.4.12" }
tracing-appender_v0_2 = { package = "tracing-appender", version = "0.2.2" }
tracing-opentelemetry_v0_21 = { package = "tracing-opentelemetry", version = "0.21" }
tracing-subscriber_v0_3 = { package = "tracing-subscriber", features = ["ansi", "env-filter", "fmt", "json", "registry", "smallvec", "std", "time"], default-features = false, version = "0.3.15" }
tracing_v0_1 = { package = "tracing", version = "0.1.37" }
uint_v0_9 = { package = "uint", version = "0.9.4" }
uuid_v1 = { package = "uuid", features = ["fast-rng", "v4"], version = "1.1.2" }
x509-parser_v0_14 = { package = "x509-parser", version = "0.14" }

# Local patches - typically git references
[patch.crates-io]
