
[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anemo_0_0_0 = {git="https://github.com/mystenlabs/anemo.git",rev="1169850e6af127397068cd86764c29b1d49dbe35",package="anemo"}
anyhow_1_0_71 = {version="1.0.71",package="anyhow",features=["backtrace"]}
arbitrary_1_3_0 = {version="1.3.0",package="arbitrary",features=["derive"]}
async-trait_0_1_73 = {version="0.1.73",package="async-trait"}
atomic_float_0_1_0 = {version="0.1.0",package="atomic_float"}
axum-server_0_5_1 = {version="0.5.1",package="axum-server",features=["tls-rustls"]}
axum_0_6_20 = {version="0.6.20",package="axum",features=["headers","http2","ws"]}
bcs_0_1_4 = {version="0.1.4",package="bcs"}
bincode_1_3_3 = {version="1.3.3",package="bincode"}
byteorder_1_4_3 = {version="1.4.3",package="byteorder",features=["i128"]}
bytes-varint_1_0_3 = {version="1.0.3",package="bytes-varint"}
bytes_1_4_0 = {version="1.4.0",package="bytes",features=["serde"]}
cfg-if_1_0_0 = {version="1.0.0",package="cfg-if"}
clap_4_4_1 = {version="4.4.1",package="clap",features=["derive","wrap_help"]}
codespan-reporting_0_11_1 = {version="0.11.1",package="codespan-reporting",features=["serialization"]}
codespan_0_11_1 = {version="0.11.1",package="codespan",features=["serialization"]}
colored_2_0_4 = {version="2.0.4",package="colored"}
const-str_0_5_6 = {version="0.5.6",package="const-str"}
crossterm_0_25_0 = {version="0.25.0",package="crossterm"}
dashmap_5_4_0 = {version="5.4.0",package="dashmap"}
derivative_2_2_0 = {version="2.2.0",package="derivative"}
derive_more_0_99_17 = {version="0.99.17",package="derive_more"}
difference_2_0_0 = {version="2.0.0",package="difference"}
dirs-next_2_0_0 = {version="2.0.0",package="dirs-next"}
ed25519-consensus_2_1_0 = {version="2.1.0",package="ed25519-consensus"}
ed25519_1_5_3 = {version="1.5.3",package="ed25519",features=["alloc","serde","zeroize"]}
enum_dispatch_0_3_9 = {version="0.3.9",package="enum_dispatch"}
ethnum_1_3_2 = {version="1.3.2",package="ethnum"}
eyre_0_6_8 = {version="0.6.8",package="eyre"}
fastcrypto-tbls_0_1_0 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto-tbls"}
fastcrypto-zkp_0_1_2 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto-zkp"}
fastcrypto_0_1_7 = {git="https://github.com/MystenLabs/fastcrypto",rev="643831ec3b67bdd2b5f998c0bec1b7c91823351f",package="fastcrypto",features=["beacon-dkg","copy_key"]}
futures_0_3_29 = {version="0.3.29",package="futures",features=["bilock","unstable"]}
git-version_0_3_5 = {version="0.3.5",package="git-version"}
hashbrown_0_12_3 = {version="0.12.3",package="hashbrown",features=["raw"]}
hex_0_4_3 = {version="0.4.3",package="hex",features=["serde"]}
http-body_0_4_5 = {version="0.4.5",package="http-body"}
http_0_2_9 = {version="0.2.9",package="http"}
hyper_0_14_26 = {version="0.14.26",package="hyper",features=["full"]}
im_15_1_0 = {version="15.1.0",package="im"}
impl-trait-for-tuples_0_2_2 = {version="0.2.2",package="impl-trait-for-tuples"}
indexmap_1_9_3 = {version="1.9.3",package="indexmap",features=["serde","std"]}
insta_1_26_0 = {version="1.26.0",package="insta",features=["json","redactions","yaml"]}
itertools_0_10_5 = {version="0.10.5",package="itertools"}
log_0_4_20 = {version="0.4.20",package="log",features=["serde","std"]}
match_opt_0_1_2 = {version="0.1.2",package="match_opt"}
multiaddr_0_17_0 = {version="0.17.0",package="multiaddr"}
num-bigint_0_4_3 = {version="0.4.3",package="num-bigint",features=["rand"]}
num_0_4_1 = {version="0.4.1",package="num"}
once_cell_1_18_0 = {version="1.18.0",package="once_cell",features=["unstable","unstable","unstable"]}
opentelemetry-otlp_0_13_0 = {version="0.13.0",package="opentelemetry-otlp"}
opentelemetry-proto_0_3_0 = {version="0.3.0",package="opentelemetry-proto",features=["gen-tonic","traces"]}
opentelemetry_0_20_0 = {version="0.20.0",package="opentelemetry",features=["metrics","rt-tokio"]}
opentelemetry_api_0_20_0 = {version="0.20.0",package="opentelemetry_api",features=["logs","metrics"]}
ouroboros_0_17_2 = {version="0.17.2",package="ouroboros"}
parking_lot_0_12_1 = {version="0.12.1",package="parking_lot"}
petgraph_0_5_1 = {version="0.5.1",package="petgraph"}
phf_0_11_1 = {version="0.11.1",package="phf",features=["macros","uncased"]}
pkcs8_0_9_0 = {version="0.9.0",package="pkcs8",features=["pem","std"]}
primitive-types_0_10_1 = {version="0.10.1",package="primitive-types",features=["impl-serde"]}
proc-macro2_1_0_66 = {version="1.0.66",package="proc-macro2",features=["span-locations"]}
prometheus_0_13_3 = {version="0.13.3",package="prometheus"}
proptest-derive_0_3_0 = {version="0.3.0",package="proptest-derive"}
proptest_1_1_0 = {version="1.1.0",package="proptest"}
prost_0_11_9 = {version="0.11.9",package="prost"}
prost_0_12_1 = {version="0.12.1",package="prost"}
protobuf_2_28_0 = {version="2.28.0",package="protobuf",features=["with-bytes"]}
quote_1_0_33 = {version="1.0.33",package="quote"}
rand_0_8_5 = {version="0.8.5",package="rand",features=["small_rng"]}
rcgen_0_9_3 = {version="0.9.3",package="rcgen"}
ref-cast_1_0_14 = {version="1.0.14",package="ref-cast"}
regex_1_8_4 = {version="1.8.4",package="regex"}
reqwest_0_11_20 = {version="0.11.20",package="reqwest",features=["blocking","json","rustls-tls"]}
roaring_0_10_1 = {version="0.10.1",package="roaring"}
rustls-pemfile_1_0_2 = {version="1.0.2",package="rustls-pemfile"}
rustls-webpki_0_101_4 = {version="0.101.4",package="rustls-webpki"}
rustls_0_21_6 = {version="0.21.6",package="rustls",features=["dangerous_configuration","quic"]}
schemars_0_8_12 = {version="0.8.12",package="schemars",features=["either"]}
scopeguard_1_1_0 = {version="1.1.0",package="scopeguard"}
serde-name_0_2_1 = {version="0.2.1",package="serde-name"}
serde-reflection_0_3_6 = {version="0.3.6",package="serde-reflection"}
serde_1_0_190 = {version="1.0.190",package="serde",features=["alloc","derive","rc"]}
serde_bytes_0_11_9 = {version="0.11.9",package="serde_bytes"}
serde_json_1_0_95 = {version="1.0.95",package="serde_json",features=["alloc","arbitrary_precision","preserve_order","raw_value","unbounded_depth"]}
serde_repr_0_1_10 = {version="0.1.10",package="serde_repr"}
serde_with_2_1_0 = {version="2.1.0",package="serde_with",features=["hex"]}
serde_yaml_0_8_26 = {version="0.8.26",package="serde_yaml"}
sha2_0_9_9 = {version="0.9.9",package="sha2"}
signature_1_6_4 = {version="1.6.4",package="signature",features=["digest-preview","hazmat-preview","rand-preview"]}
smallvec_1_10_0 = {version="1.10.0",package="smallvec"}
snap_1_1_0 = {version="1.1.0",package="snap"}
static_assertions_1_1_0 = {version="1.1.0",package="static_assertions"}
strum_0_24_1 = {version="0.24.1",package="strum",features=["derive"]}
strum_macros_0_24_3 = {version="0.24.3",package="strum_macros"}
syn_1_0_107 = {version="1.0.107",package="syn",features=["extra-traits","fold","full","visit","visit-mut"]}
syn_2_0_32 = {version="2.0.32",package="syn", features = ["full", "fold", "extra-traits"]}
synstructure_0_12_6 = {version="0.12.6",package="synstructure"}
tap_1_0_1 = {version="1.0.1",package="tap"}
tempfile_3_8_0 = {version="3.8.0",package="tempfile"}
thiserror_1_0_50 = {version="1.0.50",package="thiserror"}
tokio-rustls_0_24_0 = {version="0.24.0",package="tokio-rustls"}
tokio-stream_0_1_14 = {version="0.1.14",package="tokio-stream",features=["net","sync"]}
tokio_1_28_1 = {version="1.28.1",package="tokio",features=["full","test-util","tracing"]}
tonic-health_0_10_2 = {version="0.10.2",package="tonic-health"}
tonic_0_10_0 = {version="0.10.0",package="tonic",features=["tls"]}
tonic_0_9_2 = {version="0.9.2",package="tonic"}
tower-http_0_3_5 = {version="0.3.5",package="tower-http",features=["full"]}
tower-layer_0_3_2 = {version="0.3.2",package="tower-layer"}
tower_0_4_13 = {version="0.4.13",package="tower",features=["full"]}
tracing-appender_0_2_2 = {version="0.2.2",package="tracing-appender"}
tracing-opentelemetry_0_21_0 = {version="0.21.0",package="tracing-opentelemetry"}
tracing-subscriber_0_3_17 = {version="0.3.17",package="tracing-subscriber",features=["env-filter","json","time"]}
tracing_0_1_37 = {version="0.1.37",package="tracing",features=["log"]}
uint_0_9_5 = {version="0.9.5",package="uint"}
uuid_1_2_2 = {version="1.2.2",package="uuid",features=["fast-rng","v4"]}
variant_count_1_1_0 = {version="1.1.0",package="variant_count"}
walkdir_2_3_2 = {version="2.3.2",package="walkdir"}
x509-parser_0_14_0 = {version="0.14.0",package="x509-parser"}
# hard-coded in buckify template
libc = "0.2"
# Local patches - typically git references
[patch.crates-io]
