[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
hex = "0.4.3"
axum = { version = "0.6.6", default-features = false, features = [
    "headers",
    "tokio",
    "http1",
    "http2",
    "json",
    "matched-path",
    "original-uri",
    "form",
    "query",
    "ws",
] }
axum-server = { version = "0.5.1", default-features = false, features = [
    "tls-rustls",
] }
anyhow = { version = "1.0.64", features = ["backtrace"] }
tokio = { version = "1.32", features = [
    "bytes",
    "default",
    "fs",
    "full",
    "io-std",
    "io-util",
    "libc",
    "macros",
    "mio",
    "net",
    "num_cpus",
    "rt",
    "rt-multi-thread",
    "socket2",
    "sync",
    "time",
    "tokio-macros",
    "tracing",
    "windows-sys",
] }
tokio-stream = { version = "0.1.14", features = ["sync", "net"] }
clap = { version = "4.4", features = ["derive", "wrap_help"] }
reqwest = { version = "0.11.20", default_features = false, features = [
    "blocking",
    "json",
    "rustls-tls",
] }
prometheus-parse = { git = "https://github.com/suiwombat/prometheus-parse-rs.git" }
prometheus = "0.13.3"
const-str = "0.5.3"
mio = "0.8.8"
socket2 = "0.5.4"
libc = "0.2"
bytes = "1.4.0"
protobuf = { version = "2.28", features = ["with-bytes"] }
tracing = "0.1.37"
tower = { version = "0.4.12", features = [
    "full",
    "util",
    "timeout",
    "load-shed",
    "limit",
] }
tower-http = { version = "0.3.4", features = [
    "cors",
    "full",
    "trace",
    "set-header",
    "propagate-header",
] }
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = { version = "1.0.95", features = [
    "preserve_order",
    "arbitrary_precision",
] }
serde_with = { version = "2.1.0", features = ["hex"] }
serde_yaml = "0.8.26"
serde-name = "0.2.1"
serde_bytes = "0.11"
git-version = "0.3.5"
itertools = "0.10.5"
rand = "0.8.5"
hyper = "0.14.20"
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http2"] }
multiaddr = "0.17.0"
snap = "1.1.0"
rustls = { version = "0.21.6", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.2"
once_cell = "1.18.0"
http = "0.2.8"
http-body = "0.4.5"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc", features = ["beacon-dkg", "copy_key"] }
fastcrypto-derive = { git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc", default-features = false }
fastcrypto-tbls = { git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc" }
fastcrypto-zkp = { git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc", default-features = false }
unicase = "2.4.0"
version_check = "0.9"
android-tzdata = "0.1.1"
android_system_properties = "0.1.5"
bumpalo = "3.14.0"
tap = "1.0.1"
dashmap = "5.4.0"
parking_lot = "0.12.1"
async-trait = "0.1.61"
futures = "0.3.25"
futures-core = "0.3.21"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
scopeguard = "1.1"
anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "1169850e6af127397068cd86764c29b1d49dbe35" }
anemo-build = { git = "https://github.com/mystenlabs/anemo.git", rev = "1169850e6af127397068cd86764c29b1d49dbe35" }
anemo-tower = { git = "https://github.com/mystenlabs/anemo.git", rev = "1169850e6af127397068cd86764c29b1d49dbe35" }
bincode = "1.3.3"
bcs = "0.1.4"
byteorder = "1.4.3"
im = "15"
thiserror = "1.0.40"
signature = "1.6.0"
signature_2_0_0 = { version = "2.0.0", package = "signature"}
static_assertions = "1.1.0"
schemars = { version = "0.8.10", features = ["either"] }
tonic = { version = "0.8.2", features = ["transport", "tls"] }
tonic-build = { version = "0.8.2", features = ["prost", "transport"] }
tonic-health = "0.8.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24.3"
roaring = "0.10.1"
enum_dispatch = "^0.3"
eyre = "0.6.8"
indexmap = { version = "1.9.2", features = ["serde"] }
derivative = "2.2.0"
getrandom = { version = "0.2", features = ["js"] }
arbitrary = "1.3.0"
variant_count = "1.1"
ref-cast = "1.0"
proptest = "1.2.0"
proptest-derive = "0.4"
syn = { version = "2", features = ["full", "derive", "fold", "extra-traits"] }
syn_1 = { package = "syn", version = "1", features = [
    "full",
    "derive",
    "fold",
    "extra-traits",
] }
quote = "1.0"
ethnum = "1.0.4"
primitive-types = { version = "0.10.1", features = ["impl-serde"] }
uint = "0.9.4"
num = "0.4.0"
petgraph = "0.5.1"
serde-reflection = "0.3.2"
difference = "2.0.0"
walkdir = "2.3.1"
sha2 = "0.9.3"
num-bigint = "0.4.0"
dirs-next = "2.0.0"
derive_more = "0.99.17"
phf = { version = "0.11", features = ["macros"] }
colored = "2.0.0"
codespan-reporting = "0.11.1"
# regex = "1.5.5"
regex = "1.7.1"
tempfile = "3.2.0"
log = { version = "0.4.14", features = ["serde"] }
ouroboros = "0.17.2"
codespan = { version = "0.11.1", features = ["serialization"] }
smallvec = "1.6.1"
proc-macro2 = "1.0.47"
rocksdb = { version = "0.21.0", features = [
    "snappy",
    # "lz4",
    # "zstd",
    # "zlib",
    # "multi-threaded-cf",
], default-features = false }
hdrhistogram = "7.5.1"
fdlimit = "0.2.1"
collectable = "0.0.2"
serde_repr = "0.1"
insta = { version = "1.21.1", features = ["redactions", "yaml", "json"] }
ed25519 = { version = "1.5.0", features = ["pkcs8", "alloc", "zeroize"] }
ed25519-consensus = { version = "2.0.1", features = ["serde"] }
impl-trait-for-tuples = "0.2.0"
hashbrown = "0.12"
cfg-if = "1.0.0"
synstructure = "0.12"
match_opt = "0.1.2"
pkcs8 = { version = "0.9.0", features = ["std"] }
rcgen = "0.9.2"
webpki = { version = "0.101.0", package = "rustls-webpki", features = [
    "alloc",
    "std",
] }
x509-parser = "0.14.0"
tower-layer = "0.3.2"
tokio-rustls = "0.24"
console-subscriber = "0.1.6"
crossterm = "0.25.0"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", default-features = false, features = [
    "std",
    "smallvec",
    "fmt",
    "ansi",
    "time",
    "json",
    "registry",
    "env-filter",
] }
atomic_float = { version = "0.1" }
bytes-varint = { version = "1", default-features = false }
tracing-opentelemetry = { version = "0.21" }
opentelemetry = { version = "0.20", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.13" }
opentelemetry-proto = { version = "0.3", features = ["gen-tonic", "traces"] }
opentelemetry_api = { version = "0.20", features = ["logs", "metrics"] }
prost = "0.11.8"
prost-build = "0.11.8"
ring_16_20 = { package = "ring", version = "0.16.20", features = [
    "alloc",
    "dev_urandom_fallback",
] }
ring = { package = "ring", version = "0.17.0", features = [
    "alloc",
    "dev_urandom_fallback",
] }
# compiler_builtins = { git = "https://github.com/rust-lang/compiler-builtins" }
arc-swap = { version = "1.5.1", features = ["serde"] }
url = "2.3.1"
dirs = "4.0.0"
csv = "1.2.1"
integer-encoding = "3.0.1"
internment = { version = "0.5.0", features = ["arc"] }
num_enum = "0.6.1"
object_store = { version = "0.7", features = ["aws", "gcp", "azure"] }
backoff = { version = "0.4.0", features = [
    "futures",
    "futures-core",
    "pin-project-lite",
    "tokio",
    "tokio_1",
] }
base64-url = "2"
lru = "0.10"
zstd = "0.12.3"
zstd-safe = { version = "6", default-features = false, features = ["arrays", "legacy", "std", "zdict_builder"] }
secp256k1 = { version = "0.27", features = ["bitcoin_hashes", "global-context", "rand-std", "recovery"] }
secp256k1-sys = { version = "0.8", default-features = false, features = ["recovery", "std"] }
linked-hash-map = "0.5.6"
treeline = "0.1.0"
named-lock = "0.2.0"
toml = "0.5.8"
heck = "0.3.2"
whoami = "1.2.1"
cached = "0.43.0"
tokio-retry = "0.3"
sha3 = "0.10.8"
sha3_0_9_1 = { package = "sha3", version = "0.9.1" }
fail = "0.4.0"
better_any = "0.1.1"
simplelog = "0.9.0"
paste = "1.0.5"
tera = "1.16.0"
pretty = "0.10.0"
leb128 = "0.2.5"
camino = "1.1.1"
mockall = "0.11.4"
derive_builder = "0.12.0"
base64 = "0.21.2"
quinn-proto = "^0.10.5"
indicatif = "0.17.2"
governor = "0.6.0"
num_cpus = "1.15.0"
tiny-bip39 = "1.0.0"
bip32 = "0.4.0"
slip10_ed25519 = "0.1.3"
either = "1.8.0"
chrono = { version = "0.4.26", features = ["clock", "serde"] }
rustversion = "1.0.9"
protobuf-src = "1.1.0"
aws-config = "0.56"
aws-sdk-dynamodb = "0.29.0"
aws-sdk-s3 = "0.29.0"
unescape = "0.1.0"
derive-syn-parse = "0.1.5"
versions = "4.1.0"
jsonrpsee = { git = "https://github.com/wlmyng/jsonrpsee.git", rev = "b1b300784795f6a64d0fcdf8f03081a9bc38bde8", features = [
    "server",
    "macros",
    "ws-client",
    "http-client",
    "jsonrpsee-core",
] }
librocksdb-sys = "0.11.0+8.1.1"
# rustc-std-workspace-core = "1.0.0"

# Local patches - typically git references
[patch.crates-io]

