[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anemo = { package = "anemo", git = "https://github.com/mystenlabs/anemo.git", rev = "1169850e6af127397068cd86764c29b1d49dbe35", default-features = false }
anyhow = "1.0.71"
arbitrary = { features = ["derive"], default-features = false, version = "1" }
async-trait = "0.1.61"
atomic_float = "0.1"
axum = { features = ["headers", "tokio", "http1", "http2", "json", "matched-path", "original-uri", "form", "query", "ws"], default-features = false, version = "0.6.6" }
axum-server = { features = ["tls-rustls"], default-features = false, version = "0.5.1" }
bcs = "0.1.4"
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.4"
bytes-varint = { default-features = false, version = "1" }
cfg-if = "1"
clap = { features = ["derive", "wrap_help"], version = "4.4" }
codespan = { features = ["serialization"], default-features = false, version = "0.11" }
codespan-reporting = { features = ["serialization"], default-features = false, version = "0.11" }
colored = "2"
console-subscriber = "0.2"
const-str = "0.5.3"
crossterm = "0.25"
dashmap = "5.4"
derivative = "2.2"
derive_more = "0.99.17"
difference = "2"
dirs-next = { default-features = false, version = "2" }
ed25519 = { features = ["pkcs8", "alloc", "zeroize"], version = "1.5" }
ed25519-consensus = { features = ["serde"], version = "2.0.1" }
enum_dispatch = "0.3"
ethnum = { default-features = false, version = "1" }
eyre = "0.6.8"
fastcrypto = { package = "fastcrypto", git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc", features = ["beacon-dkg", "copy_key"] }
fastcrypto-tbls = { package = "fastcrypto-tbls", git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc" }
fastcrypto-zkp = { package = "fastcrypto-zkp", git = "https://github.com/MystenLabs/fastcrypto", rev = "517ec93ad2eba1807c9508f14953814a33523edc", default-features = false }
futures = "0.3.28"
getrandom = { features = ["std"], default-features = false, version = "0.2" }
git-version = "0.3.5"
hashbrown = "0.12"
hex = "0.4.3"
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.20"
im = "15"
impl-trait-for-tuples = "0.2"
indexmap = { features = ["serde"], version = "1.9.2" }
insta = { features = ["redactions", "yaml", "json"], version = "1.21.1" }
itertools = "0.10.5"
libc = "0.2"
log = { features = ["serde", "std"], default-features = false, version = "0.4" }
match_opt = "0.1.2"
multiaddr = "0.17"
num = "0.4"
num-bigint = "0.4.3"
once_cell = "1.18"
opentelemetry = { features = ["metrics", "rt-tokio"], version = "0.20" }
opentelemetry-otlp = { features = ["grpc-tonic"], version = "0.13" }
opentelemetry-proto = { features = ["gen-tonic", "traces"], version = "0.3" }
opentelemetry_api = { features = ["logs", "metrics"], version = "0.20" }
ouroboros = "0.17"
parking_lot = "0.12.1"
petgraph = "0.5.1"
phf = { features = ["macros", "uncased"], version = "0.11" }
pkcs8 = { features = ["std"], version = "0.9" }
primitive-types = { features = ["impl-serde"], version = "0.10" }
proc-macro2 = "1.0.47"
prometheus = "0.13.3"
proptest = "1.1"
proptest-derive = "0.3"
prost = "0.12.1"
prost-build = "0.12.1"
prost_0_11 = { package = "prost", version = "0.11" }
protobuf = { features = ["with-bytes"], version = "2.28" }
quote = "1.0.23"
rand = "0.8.5"
rcgen = "0.9.2"
ref-cast = { default-features = false, version = "1" }
regex = "1.7.1"
reqwest = { features = ["blocking", "json", "rustls-tls"], version = "0.11.20" }
roaring = "0.10.1"
rustls = { features = ["dangerous_configuration"], version = "0.21.6" }
rustls-pemfile = "1.0.2"
schemars = { features = ["either"], version = "0.8.10" }
scopeguard = "1.1"
serde = { features = ["derive", "rc"], version = "1.0.144" }
serde-name = "0.2.1"
serde-reflection = "0.3.6"
serde_bytes = "0.11"
serde_json = { features = ["preserve_order", "arbitrary_precision"], version = "1.0.95" }
serde_repr = "0.1"
serde_with = { features = ["hex"], version = "2.1" }
serde_yaml = "0.8.26"
sha2 = { features = ["oid"], version = "0.10" }
signature = "1.6"
smallvec = "1.10"
snap = "1.1"
static_assertions = "1.1"
strum = { features = ["derive"], version = "0.24" }
strum_macros = "0.24.3"
syn = { features = ["full", "derive", "extra-traits"], version = "1.0.104" }
syn_2 = { package = "syn", features = ["extra-traits", "fold", "full", "visit", "visit-mut"], version = "2" }
synstructure = "0.12"
tap = "1.0.1"
tempfile = "3.3"
thiserror = "1.0.40"
tokio = "1.28.1"
tokio-rustls = "0.24"
tokio-stream = { features = ["sync", "net"], version = "0.1.14" }
tonic = { features = ["transport", "tls"], version = "0.10" }
tonic-health = "0.10"
tonic_0_9 = { package = "tonic", version = "0.9" }
tower = { features = ["full", "util", "timeout", "load-shed", "limit"], version = "0.4.12" }
tower-http = { features = ["cors", "full", "trace", "set-header", "propagate-header"], version = "0.3.4" }
tower-layer = "0.3.2"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-opentelemetry = "0.21"
tracing-subscriber = { features = ["std", "smallvec", "fmt", "ansi", "time", "json", "registry", "env-filter"], default-features = false, version = "0.3.15" }
uint = "0.9.4"
uuid = { features = ["v4", "fast-rng"], version = "1.1.2" }
variant_count = { default-features = false, version = "1" }
walkdir = { default-features = false, version = "2" }
webpki = { package = "rustls-webpki", features = ["alloc", "std"], version = "0.101" }
x509-parser = "0.14"

# Local patches - typically git references
[patch.crates-io]
