
deps = [
    "//third-party:futures_0_3_29",
    "//third-party:parking_lot_0_12_1",
    "//third-party:tokio_1_28_1"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
    "CARGO_PKG_NAME": "mysten-common",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "mysten-common",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    deps = deps,
    edition = "2021",
    visibility = ["PUBLIC"]
)
