# load("//third-party/macros:rust_third_party.bzl", "third_party_rust_cxx_library")
rust_binary(
    name="test_ring",
    srcs = glob(["src/**/*.rs"]),
    env={
        "CARGO_PKG_AUTHORS": "Mysten Labs <build@mystenlabs.com>",
        "CARGO_BIN_NAME": "sui-proxy",
        "CARGO_PKG_VERSION": "0.0.2",
        "CARGO_PKG_NAME": "sui-proxy",
    },
    deps = [
        "//third-party:ring_16_20",
    ],
    rustc_flags = [
        "-Clink-arg=buck-out/v2/gen/root/524f8da68ea2a374/third-party/__ring-0.16.20-build-script-run__/OUT_DIR/libring-core.a",
        "-Ldependency=buck-out/v2/gen/root/524f8da68ea2a374/third-party/__ring-0.16.20-build-script-run__/OUT_DIR",
    ],
    edition = "2021",
    visibility=["PUBLIC"],
)
