# load("//third-party/macros:rust_third_party.bzl", "third_party_rust_cxx_library")
rust_binary(
    name="test_ring",
    srcs = glob(["src/**/*.rs"]),
    env={
        "CARGO_PKG_AUTHORS": "Mysten Labs <build@mystenlabs.com>",
        "CARGO_BIN_NAME": "sui-proxy",
        "CARGO_PKG_VERSION": "0.0.2",
        "CARGO_PKG_NAME": "sui-proxy",
    },
    deps = [
        "//third-party:ring",
        # ":untrusted",
        # ":ring",
    ],
    edition = "2021",
    visibility=["PUBLIC"],
)
