
deps = [
    "//crates/sui-macros:sui-macros",
    "//crates/sui-protocol-config:sui-protocol-config",
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-bytecode-utils:move-bytecode-utils",
    "//external-crates/move/crates/move-bytecode-verifier:move-bytecode-verifier",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-vm-config:move-vm-config",
    "//external-crates/move/crates/move-vm-profiler:move-vm-profiler",
    "//external-crates/move/crates/move-vm-runtime:move-vm-runtime",
    "//external-crates/move/crates/move-vm-types:move-vm-types",
    "//third-party:anyhow",
    "//third-party:bcs",
    "//third-party:leb128",
    "//third-party:parking_lot",
    "//third-party:serde",
    "//third-party:tracing"
]
named_deps = {
    "sui-move-natives": "//sui-execution/latest/sui-move-natives:sui-move-natives-latest",
    "sui-verifier": "//sui-execution/latest/sui-verifier:sui-verifier-latest"
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <eng@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Adapter and accompanying CLI for local sui development",
    "CARGO_PKG_NAME": "sui-adapter-latest",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "sui-adapter-latest",
    env = env,
    deps = deps,
    named_deps = named_deps,
)
