mysten_deps = [
    "//external-crates/move/move-ir-compiler/move-ir-to-bytecode/syntax:move-ir-to-bytecode-syntax",
    "//external-crates/move/move-command-line-common:move-command-line-common",
    "//external-crates/move/move-core/types:move-core-types",
    "//external-crates/move/move-ir/types:move-ir-types",
    "//external-crates/move/move-binary-format:move-binary-format",
    "//external-crates/move/move-symbol-pool:move-symbol-pool",
    "//external-crates/move/move-ir-compiler/move-bytecode-source-map:move-bytecode-source-map",
]
rust_library(
    name="move-ir-to-bytecode",
    srcs = glob(["src/**/*.rs"]),
    deps = mysten_deps + [
        "//third-party:anyhow",
        "//third-party:log",
        "//third-party:codespan-reporting",
        "//third-party:ouroboros",
    ],
    visibility=["PUBLIC"],
)