mysten_deps = [
    "//external-crates/move/move-ir-compiler/move-bytecode-source-map:move-bytecode-source-map",
    "//external-crates/move/move-command-line-common:move-command-line-common",
    "//external-crates/move/move-core/types:move-core-types",
    "//external-crates/move/move-ir/types:move-ir-types",
    "//external-crates/move/move-binary-format:move-binary-format",
]
rust_library(
    name="move-coverage",
    srcs = glob(["src/**/*.rs"]),
    deps = mysten_deps + [
        "//third-party:petgraph",
        "//third-party:clap",
        "//third-party:serde",
        "//third-party:anyhow",
        "//third-party:colored",
        "//third-party:codespan",
        "//third-party:bcs",
    ],
    visibility=["PUBLIC"],
)