
deps = [
    "//crates/sui-protocol-config:sui-protocol-config",
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-bytecode-utils:move-bytecode-utils",
    "//external-crates/move/crates/move-bytecode-verifier:move-bytecode-verifier",
    "//external-crates/move/crates/move-command-line-common:move-command-line-common",
    "//external-crates/move/crates/move-compiler:move-compiler",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-ir-types:move-ir-types",
    "//external-crates/move/crates/move-package:move-package",
    "//external-crates/move/crates/move-symbol-pool:move-symbol-pool",
    "//third-party:anyhow_1_0_71",
    "//third-party:fastcrypto_0_1_7",
    "//third-party:serde-reflection_0_3_6",
    "//third-party:tempfile_3_8_0"
]
named_deps = {
    "sui-verifier": "//sui-execution/latest/sui-verifier:sui-verifier-latest"
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <eng@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Logic for building Sui Move Packages",
    "CARGO_PKG_NAME": "sui-move-build",
    "CARGO_PKG_VERSION": "1.16.0",
}
rust_library(
    name = "sui-move-build",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    deps = deps,
    named_deps = named_deps,
    edition = "2021",
    visibility = ["PUBLIC"]
)
