
deps = [
    "//crates/sui-types:sui-types",
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-bytecode-utils:move-bytecode-utils",
    "//external-crates/move/crates/move-bytecode-verifier:move-bytecode-verifier",
    "//external-crates/move/crates/move-command-line-common:move-command-line-common",
    "//external-crates/move/crates/move-compiler:move-compiler",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-ir-types:move-ir-types",
    "//external-crates/move/crates/move-package:move-package",
    "//external-crates/move/crates/move-symbol-pool:move-symbol-pool",
    "//third-party:anyhow",
    "//third-party:fastcrypto",
    "//third-party:serde-reflection",
    "//third-party:tempfile"
]
named_deps = {
    "sui-verifier": "//sui-execution/latest/sui-verifier:sui-verifier-latest"
}
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Mysten Labs <eng@mystenlabs.com>]",
    "CARGO_PKG_DESCRIPTION": "Logic for building Sui Move Packages",
    "CARGO_PKG_NAME": "sui-move-build",
    "CARGO_PKG_VERSION": "0.0.0",
}
rust_library(
    name = "sui-move-build",
    env = env,
    deps = deps,
    named_deps = named_deps,
)
