
deps = [
    "//external-crates/move/crates/move-binary-format:move-binary-format",
    "//external-crates/move/crates/move-bytecode-source-map:move-bytecode-source-map",
    "//external-crates/move/crates/move-command-line-common:move-command-line-common",
    "//external-crates/move/crates/move-core-types:move-core-types",
    "//external-crates/move/crates/move-ir-to-bytecode-syntax:move-ir-to-bytecode-syntax",
    "//external-crates/move/crates/move-ir-types:move-ir-types",
    "//external-crates/move/crates/move-symbol-pool:move-symbol-pool",
    "//third-party:anyhow_1_0_71",
    "//third-party:codespan-reporting_0_11_1",
    "//third-party:log_0_4_20",
    "//third-party:ouroboros_0_17_2"
]
env = {
    "CARGO_MANIFEST_DIR": ".",
    "CARGO_PKG_AUTHORS": "[Diem Association <opensource@diem.com>]",
    "CARGO_PKG_DESCRIPTION": "Diem ir to bytecode",
    "CARGO_PKG_NAME": "move-ir-to-bytecode",
    "CARGO_PKG_VERSION": "0.1.0",
}
rust_library(
    name = "move-ir-to-bytecode",
    srcs = glob(["*","**/*"]),
    crate_root = "src/lib.rs",
    env = env,
    deps = deps,
    edition = "2021",
    visibility = ["PUBLIC"]
)
