[[buildscript]]
[buildscript.cxx_library]
name = "libsecp256k1-sys-macos"
srcs = [
    "depend/secp256k1/contrib/lax_der_parsing.c",
    "depend/secp256k1/src/precomputed_ecmult_gen.c",
    "depend/secp256k1/src/precomputed_ecmult.c",
    "depend/secp256k1/src/secp256k1.c",
]
include_paths = [
    "depend/secp256k1",
    "depend/secp256k1/include",
    "depend/secp256k1/src",
]

compiler_flags = ["-Wno-unused-function","-Wno-error"]

# TODO should i make these preprocessor flags? they seem to work as env vars
[env]
SECP256K1_API = ""
ECMULT_GEN_PREC_BITS = "4"
ENABLE_MODULE_ECDH = "15"
ENABLE_MODULE_SCHNORRSIG = "1"
ENABLE_MODULE_EXTRAKEYS = "1"
USE_EXTERNAL_DEFAULT_CALLBACKS = "1"
ENABLE_MODULE_RECOVERY = "1"